"""empty message

Revision ID: 386eabf941cb
Revises: e02acbf2a795
Create Date: 2024-01-02 23:25:19.076100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386eabf941cb'
down_revision = 'e02acbf2a795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('stock_name', sa.String(length=60), nullable=False),
    sa.Column('stock_symbol', sa.String(length=60), nullable=False),
    sa.Column('stock_price', sa.Float(), nullable=False),
    sa.Column('stock_open', sa.Float(), nullable=False),
    sa.Column('stock_high', sa.Float(), nullable=False),
    sa.Column('stock_low', sa.Float(), nullable=False),
    sa.Column('stock_volume', sa.Float(), nullable=False),
    sa.Column('stock_market_cap', sa.Float(), nullable=False),
    sa.Column('stock_change', sa.Float(), nullable=False),
    sa.Column('stock_change_percent', sa.Float(), nullable=False),
    sa.Column('stock_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
